/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BrowserPane: typeof import('./src/components/BrowserPane.vue')['default']
    DashboardView: typeof import('./src/components/DashboardView.vue')['default']
    LoginView: typeof import('./src/components/LoginView.vue')['default']
    NetunnelWorkspace: typeof import('./src/components/NetunnelWorkspace.vue')['default']
    SettingsPanel: typeof import('./src/components/SettingsPanel.vue')['default']
  }
}
